const jwt=require('jsonwebtoken');const db=require('../config/database');const onlineUsers=new Map();
function socketAuth(socket,next){try{const token=socket.handshake.auth.token||socket.handshake.headers.cookie?.match(/(?:^|; )token=([^;]*)/)?.[1];const p=jwt.verify(token,process.env.JWT_SECRET);const u=db.prepare('SELECT id,name,username FROM users WHERE id=?').get(p.id);if(!u)return next(new Error('Unauthorized'));socket.user=u;next();}catch{return next(new Error('Unauthorized'));}}
function register(io){io.use(socketAuth);io.on('connection',socket=>{const u=socket.user;onlineUsers.set(String(u.id),socket.id);socket.emit('online-users',{userIds:[...onlineUsers.keys()].map(Number)});io.emit('user-online',{userId:u.id});
 socket.on('call-user',({targetId,callType,callId})=>{const target=onlineUsers.get(String(targetId));if(!target)return socket.emit('call-unavailable',{reason:'User is offline.'});if(!['voice','video'].includes(callType))return socket.emit('call-unavailable',{reason:'This call type is not supported.'});const caller={id:u.id,name:u.name,username:u.username};io.to(target).emit('incoming-call',{from:caller,callType,callId});});
 ['accept-call','reject-call','end-call','video-offer','video-answer','voice-offer','voice-answer','ice-candidate','camera-on','camera-off','screen-share-started','screen-share-stopped'].forEach(event=>socket.on(event,({targetId,...data})=>{const target=onlineUsers.get(String(targetId));if(target)io.to(target).emit(event,{from:u,...data});}));
 socket.on('join-room',({roomId})=>{socket.join(`room:${roomId}`);socket.to(`room:${roomId}`).emit('participant-joined',{participant:u});const peers=[...io.sockets.adapter.rooms.get(`room:${roomId}`)||[]].filter(id=>id!==socket.id).map(id=>io.sockets.sockets.get(id)?.user).filter(Boolean);socket.emit('room-participants',{participants:peers});});
 socket.on('leave-room',({roomId})=>{socket.leave(`room:${roomId}`);socket.to(`room:${roomId}`).emit('participant-left',{participant:u});});
 socket.on('meeting-message',({roomId,message})=>io.to(`room:${roomId}`).emit('meeting-message',{sender:u,message,createdAt:new Date().toISOString()}));
 socket.on('typing',({roomId})=>socket.to(`room:${roomId}`).emit('typing',{user:u}));socket.on('stop-typing',({roomId})=>socket.to(`room:${roomId}`).emit('stop-typing',{user:u}));
 socket.on('disconnect',()=>{if(onlineUsers.get(String(u.id))===socket.id){onlineUsers.delete(String(u.id));io.emit('user-offline',{userId:u.id});}for(const room of socket.rooms)if(room.startsWith('room:'))socket.to(room).emit('participant-left',{participant:u});});});}
module.exports={register,onlineUsers};
